### PR TITLE
Added Firebase Analytics gtag

### PR DESCRIPTION
**Pull request by anyatokar**
~#27 should be merged first~

~I added the `gtag` per instructions: https://developers.google.com/analytics/devguides/collection/gtagjs/
and https://support.google.com/analytics/answer/9304153#add-tag&zippy=%2Cadd-the-google-tag-directly-to-your-web-pages~ 

**Update:**
- #89 should be merged first :)
- new gtag instructions link: https://developers.google.com/tag-platform/gtagjs/install
- disabled the collection of personalized advertising data and restricted data processing on gtag per PR feedback https://support.google.com/google-ads/answer/9606827#zippy=%2Cedit-your-google-tag-to-enable-restricted-data-processing

Screen Shot 2022-09-17 at 7 40 21 PM

### CODE REVIEW

**Comment by mmcknett** [comment]
Hmm, if we start collecting analytics information, we ought to create a privacy policy and be clear about what information will be collected and for what purpose. Are we thinking about trying to get an idea of where users are, regionally? Are we trying to get an idea of MAU or DAU? I feel skepticism about adding analytics without those specific goals in mind, or without communicating it in a public policy.

**Comment by anyatokar** [comment]
> Hmm, if we start collecting analytics information, we ought to create a privacy policy and be clear about what information will be collected and for what purpose. Are we thinking about trying to get an idea of where users are, regionally? Are we trying to get an idea of MAU or DAU? I feel skepticism about adding analytics without those specific goals in mind, or without communicating it in a public policy.

@mmcknett that's a good point, I agree, we could be more intentional and open about this. I think MAU, DAU, regional use, and how much time is spent on the page would be helpful to know. I can do some research and draft a policy. I don't know if you have examples in mind? The reason for tracking analytics is to have more quantitative data to back up the app's usefulness to the Seattle community. The more useful it is, the more incentive to continue improving it. What do you think?

**Comment by mmcknett** [comment]
There's some configuration options on the gtag that I think we probably want to make sure are enabled. Specifically, I think we should ensure that we do: [Disable the collection of personalized advertising data](https://support.google.com/google-ads/answer/9606827#zippy=%2Cedit-your-google-tag-to-enable-restricted-data-processing).

Even though we're not specifically targeting EU users, I think we'd benefit from following the guidelines Google has set up for seeking consent for collection of personal information: [EU user consent policy](https://www.google.com/about/company/user-consent-policy/).

Here are some proposals that come to mind after reading through advice about privacy policies & statements:
* We ought to add a notice of what information we store with Google (both in firestore and now in Google Analytics)
  - Also, I think it's appropriate for us to have a description of the reasons we're collecting the info (as you described above -- basically, we want to measure the app's success by how many people are using it, from where, how often, and for how long)
* We ought to make it clear how users would be able to delete information collected about them from firestore and GA. Though I don't think it is possible to delete information about them from GA, since I don't *think* we'd be able to (by design) attribute any particular data to them, so it wouldn't be possible to *only* delete their data.
  - So for analytics, we ought to say that if they do not want to contribute to the usage-by-demographic data, then they should either...
    - opt out of GA collection (and we should provide a mechanism to do that)
    - install an ad blocker (e.g. I run [uBlock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en), and it looks like that outright denies loading of anything from googletagmanager.com)
    - stop using the page
    - OR any combination of those things
  - and for Firestore we ought to make a way for users to delete their saved data and delete their user account. We could probably, in the interim, just have a process for users to request deletion and have us do it manually for anyone who requests
* We probably want to create a privacy statement for ^ that is accessible on the site, and then I think it would also be cool to summarize that statement when users create accounts.
* And after we create the privacy statement, we probably should email existing users to tell them about the demographic tracking and explain how they can opt out.

**Comment by anyatokar** [comment]
> * and for Firestore we ought to make a way for users to delete their saved data and delete their user account. We could probably, in the interim, just have a process for users to request deletion and have us do it manually for anyone who requests

Regarding this part, in top right nav>Profile>Edit Profile, the user can already delete their profile. This deletes their user account - Firebase Auth and any associated Firestore data.

Screen Shot 2024-02-28 at 11 52 20 AM

**Pull request merged**
